// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDgB3_jUVEpTv8Ts4PEyvPh_xYEvnJlQ',
    appId: '1:534609666525:web:fb0dc86926e3b9d2121634',
    messagingSenderId: '534609666525',
    projectId: 'project-blue-sky-3271b',
    authDomain: 'project-blue-sky-3271b.firebaseapp.com',
    databaseURL: 'https://project-blue-sky-3271b-default-rtdb.firebaseio.com',
    storageBucket: 'project-blue-sky-3271b.appspot.com',
    measurementId: 'G-LD5PNBSJT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CYWGuNBchiqbNQZh_KxWpkwKuKZ_BUo',
    appId: '1:534609666525:android:313b0e6c2f061683121634',
    messagingSenderId: '534609666525',
    projectId: 'project-blue-sky-3271b',
    databaseURL: 'https://project-blue-sky-3271b-default-rtdb.firebaseio.com',
    storageBucket: 'project-blue-sky-3271b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPdRHpX46ZJPwqqkpNauhMpvF_XrNXouQ',
    appId: '1:534609666525:ios:749d5c243d3166f4121634',
    messagingSenderId: '534609666525',
    projectId: 'project-blue-sky-3271b',
    databaseURL: 'https://project-blue-sky-3271b-default-rtdb.firebaseio.com',
    storageBucket: 'project-blue-sky-3271b.appspot.com',
    iosBundleId: 'com.example.projectbluesky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPdRHpX46ZJPwqqkpNauhMpvF_XrNXouQ',
    appId: '1:534609666525:ios:749d5c243d3166f4121634',
    messagingSenderId: '534609666525',
    projectId: 'project-blue-sky-3271b',
    databaseURL: 'https://project-blue-sky-3271b-default-rtdb.firebaseio.com',
    storageBucket: 'project-blue-sky-3271b.appspot.com',
    iosBundleId: 'com.example.projectbluesky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSDgB3_jUVEpTv8Ts4PEyvPh_xYEvnJlQ',
    appId: '1:534609666525:web:622708e9250259e1121634',
    messagingSenderId: '534609666525',
    projectId: 'project-blue-sky-3271b',
    authDomain: 'project-blue-sky-3271b.firebaseapp.com',
    databaseURL: 'https://project-blue-sky-3271b-default-rtdb.firebaseio.com',
    storageBucket: 'project-blue-sky-3271b.appspot.com',
    measurementId: 'G-E5W815TCVN',
  );

}